# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"path": "00_PracticalDeepLearning2019.Lesson1.ipynb",
         "fname": "00_PracticalDeepLearning2019.Lesson1.ipynb",
         "img": "00_PracticalDeepLearning2019.Lesson1.ipynb",
         "resized_image": "00_PracticalDeepLearning2019.Lesson1.ipynb",
         "pat": "00_PracticalDeepLearning2019.Lesson1.ipynb"}

modules = ["PracticalDeepLearning/Lesson1/CourseWork.py"]

doc_url = "https://hoftherose.github.io"

git_url = "https://github.com/hoftherose/FastaiV2Course/tree/master/"

def custom_doc_links(name): return None
