# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"path": "PracticalDeepLearning2019.Lesson1_Experiments.ipynb",
         "fname": "PracticalDeepLearning2019.Lesson1_Experiments.ipynb",
         "img": "PracticalDeepLearning2019.Lesson1.ipynb",
         "pat": "PracticalDeepLearning2019.Lesson1_Experiments.ipynb",
         "dblock": "PracticalDeepLearning2019.Lesson1_Experiments.ipynb",
         "dls": "PracticalDeepLearning2019.Lesson1_Experiments.ipynb"}

modules = ["PracticalDeepLearning/Lesson1/CourseWork.py",
           "PracticalDeepLearning/Lesson1/Experiments.py"]

doc_url = "https://hoftherose.github.io"

git_url = "https://github.com/hoftherose/FastaiV2Course/tree/master/"

def custom_doc_links(name): return None
