# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_PracticalDeepLearning2019.Lesson1.ipynb (unless otherwise specified).

__all__ = ['path', 'fname', 'img', 'resized_image', 'pat']

# Cell
from fastai2.data.all import *
from fastai2.vision.all import *
from nbdev.showdoc import *

# Cell
path = untar_data(URLs.PETS)

# Cell
path_anno, path_img = [path/folder for folder in path.ls()]

# Cell
fname = get_image_files(path_img)
fname[:5]

# Cell
img = Image.open(fname[0]).convert('RGB')
img

# Cell
def resized_image(fn:Path, sz=128):
    return Image.open(fn).convert('RGB').resize((sz,sz))

# Cell
pat = r'([^/]+)_\d+\.jpg$'